name: Renovate Bot GitHub Action
on:
  workflow_dispatch:
  schedule:
    - cron: "26 15 * * *"
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.11
        with:
          configurationFile: example/renovate-tester.json
          token: ${{ secrets.RENOVATE_TOKEN }}
